addSbtPlugin("com.geirsson"              % "sbt-ci-release"  % "1.5.3")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin" % "0.8.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.14")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"        % "2.2.10")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "1.6.1")
