addSbtPlugin("com.geirsson"              % "sbt-ci-release"  % "1.5.7")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin" % "0.8.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"        % "2.2.20")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"    % "2.4.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"   % "2.0.10")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"    % "0.9.27")
