name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 2.12.12
          - 2.13.5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check formatting
      if: matrix.scala == '2.13.7'
      run: sbt ++${{ matrix.scala }} scalafmtCheckAll
    - name: Run tests
      env:
        DISSONANCE_IT_TOKEN: ${{secrets.DISSONANCE_IT_TOKEN}}
      run: sbt ++${{ matrix.scala }} clean coverage test
